[package]
name = "sparsley-bench"
version = "0.0.0"
edition = "2024"
publish = false

[dev-dependencies]
bevy_ecs = { version = "=0.19.1", default-features = false }
cranelift-entity = "=0.136.2"
criterion = { version = "=0.8.2", default-features = false, features = ["cargo_bench_support", "html_reports"] }
sparsley = { path = ".." }
xsparseset = "=0.2.5"

[[bench]]
name = "compare"
harness = false

[[bench]]
name = "hot"
harness = false

[lints]
workspace = true
