[package]
name = "sparsley-diagram"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
authors = ["LilDojd <yawner@protonmail.com>"]
description = "Proc macros drawing memory diagrams of sparsley operations for rustdoc"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LilDojd/sparsley"
readme = "README.md"
keywords = ["sparse-set", "documentation", "diagram"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[lints]
workspace = true

[dev-dependencies]
trybuild = "1.0.121"
